service: precisely-react

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.common.stage}
  region: ${self:custom.common.region}
  profile: ${self:custom.common.profile}
  deploymentBucket: ${self:custom.common.deploymentBucket}

  ## Environment for handlers
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${self:custom.common.accountId}

    # REACT_APP_ env vars are made available to client-side React code;
    # Auth0 values - needed for verifying Auth0 tokens
    REACT_APP_AUTH0_DOMAIN: ${self:custom.common.auth0Tenant}.auth0.com # set in Auth0: dev-precisely, beta-precisely, prod-precisely
    REACT_APP_AUTH0_CLIENT_ID: ${self:custom.common.auth0ReactClientId}

    REACT_APP_URL: ${self:custom.common.reactURL}

resources:
  - Resources: ${file(./serverless/resources/s3-website-bucket.yml)}
  - Resources: ${file(./serverless/resources/cloudfront-distribution.yml)}
  - Resources: ${file(./serverless/resources/route53.js):Resources}

plugins:
  - serverless-finch
  - serverless-shell

custom:
  common: ${file(../serverless/common.js):vars}

  vars:
    clientDomain: ${self:custom.common.baseDomain}
    cloudfrontOriginId: "${self:provider.stage}-cloudfront"
    reactS3BucketName: reacts3.${self:custom.vars.clientDomain}

  client:
    bucketName: ${self:custom.vars.clientDomain}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html

