service: precisely-client

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: ${opt:stage, self:provider.stage}-profile-precisely
  
plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${opt:stage, self:provider.stage}-precisely-01
    distributionFolder: build
