service:
  name: precisely-client

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:provider.common.stage}
  region: ${self:provider.common.region}
  profile: ${self:provider.common.profile}

  common: ${file(../serverless/common.js):vars}

  vars:
    originId: "${self:provider.stage}-s3-origin"

    distributionBucket: ${self:provider.stage}-precisely-react

  ##
  ## Environment for handlers
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${self:provider.common.accountId}

    # REACT_APP_ env vars are made available to client-side React code;
    # Auth0 values - needed for verifying Auth0 tokens
    REACT_APP_AUTH0_DOMAIN: ${self:provider.common.auth0Tenant}.auth0.com # set in Auth0: dev-precisely, beta-precisely, prod-precisely
    REACT_APP_AUTH0_CLIENT_ID: yrNpYsLHFQ4mBHsP4rqDC8LNPLaOZDS4

    REACT_APP_URL: ${self:provider.common.reactURL}


resources:
  - Resources: ${file(./serverless/resources/cloudfront-distribution.yml)}
  - Resources: ${file(./serverless/resources/dns.yml)}

plugins:
  - serverless-finch
  - serverless-shell

custom:
  client:
    bucketName: ${self:provider.vars.distributionBucket}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html

