version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    config:
      languages:
        javascript:    
          threshold: 6
        typescript:
          threshold: 6
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:    
          count_threshold: 6
        typescript:
          count_threshold: 6
  fixme:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
exclude_patterns:
  - "app-backend/build"
  - "app-client/build"
  - "app-client/config"
  - "app-client/scripts"
  - "app-client/public"
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/__tests__/"
