---
ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: "${self:provider.stage}-graphql"
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
          MetricsEnabled: true