---
BioinformaticsECSCluster:
  Type: AWS::ECS::Cluster
  Properties:
    ClusterName: ${self:custom.vars.bioinformaticsClusterName}

BioinformaticsECSTaskDefinition:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ExecutionRoleArn:
      Fn::GetAtt: [SystemRole, Arn]
    TaskRoleArn:
      Fn::GetAtt: [SystemRole, Arn]
    Family: ${self:custom.vars.bioinformaticsECSTaskDefinitionName}
    NetworkMode: awsvpc
    Memory: 512
    Cpu: 256
    ContainerDefinitions:
      -
        Name: ${self:custom.vars.bioinformaticsContainerName}
        Memory: 512
        Cpu: 256
        Image: 416000760642.dkr.ecr.us-east-1.amazonaws.com/dev/precisely-bioinformatics:latest
        LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: BioinformaticsECSLogs
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: ${self:provider.stage}-ecs
    RequiresCompatibilities:
      - FARGATE

BioinformaticsECSService:
  Type: AWS::ECS::Service
  Properties:
    Cluster:
      Ref: BioinformaticsECSCluster
    ServiceName: ${self:provider.stage}-BioinformaticsECSService
    TaskDefinition:
      Ref: BioinformaticsECSTaskDefinition
    DesiredCount: 0
    LaunchType: FARGATE
    NetworkConfiguration:
      AwsvpcConfiguration:
        Subnets:
          - ${self:custom.vars.fullSubnetId}
