BioinformaticsECSCluster:
  Type: AWS::ECS::Cluster
  Properties:
    ClusterName: ${self:custom.vars.bioinformaticsECSClusterName}

BioinformaticsECSTask:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ExecutionRoleArn:
      Fn::GetAtt: [SystemRole, Arn]
    TaskRoleArn:
      Fn::GetAtt: [SystemRole, Arn]
    Family: ${self:custom.vars.bioinformaticsECSTaskName}
    NetworkMode: awsvpc
    Cpu: 4096
    Memory: 20480
    ContainerDefinitions:
      - Name: ${self:custom.vars.bioinformaticsECSContainerName}
        Image: 416000760642.dkr.ecr.us-east-1.amazonaws.com/dev/precisely-bioinformatics:latest
        Environment:
          - Name: AWS_S3_ENDPOINT_URL
            Value: https://s3.amazonaws.com
          - Name: S3_BUCKET_BIOINFORMATICS_UPLOAD
            Value: ${self:custom.vars.bioinformaticsUploadBucket}
          - Name: S3_BUCKET_BIOINFORMATICS_VCF
            Value: ${self:custom.vars.bioinformaticsVCFBucket}
          - Name: S3_BUCKET_BIOINFORMATICS_ERROR
            Value: ${self:custom.vars.bioinformaticsErrorBucket}
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: BioinformaticsECSLogs
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: ${self:provider.stage}-ecs-bioinformatics
    RequiresCompatibilities:
      - FARGATE

# XXX: This is configured, but currently adds no value. First, we do not have
# multiple tasks which need to execute together as a "service". Second, more
# seriously, see the AwsvpcConfiguration down there? One might expect it to
# provide reasonable defaults for tasks bound to this service, but it does no
# such thing. Running `aws ecs run-task` _requires_ this information to be
# passed in at runtime no matter what is configured here.
BioinformaticsECSService:
  Type: AWS::ECS::Service
  Properties:
    Cluster:
      Ref: BioinformaticsECSCluster
    ServiceName: ${self:provider.stage}-BioinformaticsECSService
    TaskDefinition:
      Ref: BioinformaticsECSTask
    DesiredCount: 0
    LaunchType: FARGATE
    NetworkConfiguration:
      AwsvpcConfiguration:
        AssignPublicIp: ENABLED
        Subnets:
          - ${self:custom.vars.subnetId}
        SecurityGroups:
          - ${self:custom.vars.securityGroupIdAllowInboundSSH}

BioinformaticsMetricFilterErrors:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName:
      Ref: BioinformaticsECSLogs
    FilterPattern: '{$.level="error"}'
    MetricTransformations:
      - MetricValue: 1
        MetricNamespace: Bioinformatics/Tasks
        MetricName: ${self:provider.stage}-TaskErrorCount

BioinformaticsAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmDescription: Bioinformatics task error alert
    Namespace: Bioinformatics/Tasks
    MetricName: ${self:provider.stage}-TaskErrorCount
    Statistic: Sum
    Period: 60
    EvaluationPeriods: 1
    Threshold: 0
    ComparisonOperator: GreaterThanThreshold
    TreatMissingData: notBreaching
    AlarmActions:
      - Ref: TopicErrorNotification
    # InsufficientDataActions:
    #   - Ref: TopicErrorNotification
