BioinformaticsECSCluster:
  Type: AWS::ECS::Cluster
  Properties:
    ClusterName: ${self:custom.vars.bioinformaticsECSClusterName}

BioinformaticsECSTask:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ExecutionRoleArn:
      Fn::GetAtt: [SystemRole, Arn]
    TaskRoleArn:
      Fn::GetAtt: [SystemRole, Arn]
    Family: ${self:custom.vars.bioinformaticsECSTaskName}
    NetworkMode: awsvpc
    Cpu: 4096
    Memory: 20480
    ContainerDefinitions:
      - Name: ${self:custom.vars.bioinformaticsECSContainerName}
        Image: 416000760642.dkr.ecr.us-east-1.amazonaws.com/dev/precisely-bioinformatics:latest
        Environment:
          - Name: AWS_S3_ENDPOINT_URL
            Value: https://s3.amazonaws.com
          - Name: S3_BUCKET_BIOINFORMATICS_UPLOAD
            Value: ${self:custom.vars.bioinformaticsUploadBucket}
          - Name: S3_BUCKET_BIOINFORMATICS_VCF
            Value: ${self:custom.vars.bioinformaticsVCFBucket}
          - Name: S3_BUCKET_BIOINFORMATICS_ERROR
            Value: ${self:custom.vars.bioinformaticsErrorBucket}
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: BioinformaticsECSLogs
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: ${self:provider.stage}-ecs-bioinformatics
    RequiresCompatibilities:
      - FARGATE
