---
IngestionECSCluster:
  Type: "AWS::ECS::Cluster"
  Properties:
    ClusterName: ${self:custom.vars.ingestionClusterName}

IngestionECSTaskDefinition:
  Type: "AWS::ECS::TaskDefinition"
  Properties:
    ExecutionRoleArn:
      Fn::GetAtt: [IngestionECSTaskRole, 'Arn']
    TaskRoleArn:
      Fn::GetAtt: [IngestionECSTaskRole, 'Arn']
    Family: ${self:custom.vars.ingestionECSTaskDefinitionName}
    NetworkMode: awsvpc
    Memory: 512
    Cpu: 256
    ContainerDefinitions:
      -
        Name: ${self:custom.vars.ingestionContainerName}
        Memory: 512
        Cpu: 256
        Image: 416000760642.dkr.ecr.us-east-1.amazonaws.com/dev/precisely-bioinformatics:latest
        LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: IngestionECSLogs
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: ${self:provider.stage}-ecs
    RequiresCompatibilities:
      - FARGATE

IngestionECSService:
  Type: "AWS::ECS::Service"
  Properties:
    Cluster:
      Ref: IngestionECSCluster
    ServiceName: ${self:provider.stage}-IngestionECSService
    TaskDefinition:
      Ref: IngestionECSTaskDefinition
    DesiredCount: 0
    LaunchType: FARGATE
    NetworkConfiguration:
      AwsvpcConfiguration:
        Subnets:
          - Ref: DefaultSubnetOne
          - Ref: DefaultSubnetTwo
