---
DefaultECSCluster:
  Type: "AWS::ECS::Cluster"
  Properties:
    ClusterName: ${self:provider.stage}-DefaultECSClusterName

IngestionECSTaskDefinition:
  Type: "AWS::ECS::TaskDefinition"
  Properties: 
    ExecutionRoleArn: 
      Fn::GetAtt: [IngestionECSTaskRole, 'Arn']
    TaskRoleArn: 
      Fn::GetAtt: [IngestionECSTaskRole, 'Arn']
    Family: ${self:provider.vars.ingestionECSTaskDefinitionName}
    NetworkMode: awsvpc
    Memory: 512
    Cpu: 256
    ContainerDefinitions:
      - 
        Name: ${self:provider.vars.ingestionContainerName}
        Memory: 512
        Cpu: 256
        Image: 416000760642.dkr.ecr.us-east-1.amazonaws.com/dev/precisely-bioinformatics:latest
        LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: ${self:provider.stage}-DefaultECSServiceName
              awslogs-region: 
                Ref: AWS::Region
              awslogs-stream-prefix: ${self:provider.stage}-DefaultECSServiceName
    RequiresCompatibilities:
      - FARGATE

ECSService:
  Type: "AWS::ECS::Service"
  Properties: 
    Cluster: 
      Ref: DefaultECSCluster 
    ServiceName: ${self:provider.stage}-DefaultECSServiceName
    TaskDefinition: 
      Ref: IngestionECSTaskDefinition
    DesiredCount: 0
    LaunchType: FARGATE
    NetworkConfiguration:
      AwsvpcConfiguration:
        Subnets:
          - Ref: DefaultSubnetOne
          - Ref: DefaultSubnetTwo
        AssignPublicIp: ENABLED
