S3BucketBioinformaticsUpload:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.vars.bioinformaticsUploadBucket}
    
S3BucketBioinformaticsVCF:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.vars.bioinformaticsVCFBucket}

S3BucketBioinformaticsError:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.vars.bioinformaticsErrorBucket}

BioinformaticsUploadLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName:
      # serverless adds suffix "LambdaFunction" to function names:
      Fn::GetAtt: [ BioinformaticsUploadProcessorLambdaFunction, Arn ]
    Principal: s3.amazonaws.com
    Action: lambda:InvokeFunction
    SourceAccount:
      Ref: AWS::AccountId
    SourceArn: arn:aws:s3:::${self:custom.vars.bioinformaticsUploadBucket}