S3BucketUserUpload:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:provider.vars.userUploadBucket}
S3BucketGeneticsVCF:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:provider.vars.geneticsVCFBucket}

S3BucketIngestionError:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:provider.vars.ingestionErrorBucket}

S3BucketGenetics23andMe:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:provider.vars.genetics23andMeBucket}

S3BucketGeneticsAkesogen:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:provider.vars.geneticsAkesogenBucket}

S3BucketGeneticsAncestry:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:provider.vars.geneticsAncestryBucket}

VCFIngesterLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName:
       # serverless generates this name from `functions: VCFIngester: ...`
      Fn::GetAtt: [ VCFIngesterLambdaFunction, Arn ]
    Principal: s3.amazonaws.com
    Action: lambda:InvokeFunction
    SourceAccount:
      Ref: AWS::AccountId
    SourceArn: arn:aws:s3:::${self:provider.vars.geneticsVCFBucket}

RawDataUploadLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName:
       # serverless generates this name from `functions: UserDataUpload: ...`
      Fn::GetAtt: [ RawDataUploadLambdaFunction, Arn ]
    Principal: s3.amazonaws.com
    Action: lambda:InvokeFunction
    SourceAccount:
      Ref: AWS::AccountId
    SourceArn: arn:aws:s3:::${self:provider.vars.genetics23andMeBucket}