service:
  name: precisely-aws

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.common.stage}
  region: ${self:custom.common.region}
  profile: ${self:custom.common.profile}
  deploymentBucket: ${self:custom.common.deploymentBucket}

resources:
  - Resources: ${file(./serverless/resources/network.yml)}

custom:
  common: ${file(../serverless/common.js):vars}
