service: precisely

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: ${opt:stage, self:provider.stage}-profile-precisely
  environment:
    SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}
    REGION: ${self:provider.region}
    NODE_ENV: ${opt:stage, self:provider.stage}
    AWS_PROFILE: ${opt:stage, self:provider.stage}-profile-precisely
    POSTGRES_DB_NAME: ${env:POSTGRES_DB_NAME, ''}
    POSTGRES_DB_USERNAME: ${env:POSTGRES_DB_USERNAME, ''}
    POSTGRES_DB_PASSWORD: ${env:POSTGRES_DB_PASSWORD, ''}
    POSTGRES_DB_CONN_STR: ${env:POSTGRES_DB_CONN_STR, ''}
    # Storing profile in env too as `sls invoke local` ignores the AWS profile in provider (needed for setup:database)
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
       Resource: "*"
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/*"

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-kms-secrets
  - serverless-plugin-scripts
  - serverless-offline

custom:
  scripts:
    hooks:
      'deploy:finalize': yarn setup:database -- -s ${opt:stage, self:provider.stage}
  serverless-offline:
    port: 4000
  webpackIncludeModules: true
  serverless-kms-secrets:
    secretsFile: kms-secrets/kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(./kms-secrets/kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: api
        method: post
        cors: true
        authorizer:
          arn: ${env:COGNITO_ARN, ''}
  setupDynamo:
    handler: src/data-source/dynogels-db/setup.setupDatabase
  setupPostgres:
    handler: src/data-source/postgres/setup.migrate
  deploy:
    handler: src/data-source/scripts.deploy
  ingester:
    handler: src/features/ingest/genotypeIngester.genotypeIngester
    events:
    - s3:
        bucket: ${opt:stage, 'dev'}-precisely-genetics-ga4gh
        event: s3:ObjectCreated:*
  playground:
    handler: src/handler.playgroundHandler
    events:
    - http:
        path: playground
        method: get
        cors: true
  graphiql:
    handler: src/handler.graphiqlHandler
    events:
    - http:
        path: graphiql
        method: get
        cors: true
