service: precisely

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: ${opt:stage, self:provider.stage}-profile-precisely
  environment:
    SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}
    REGION: ${self:provider.region}
    NODE_ENV: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn} 
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/users"

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-kms-secrets
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true
  serverless-kms-secrets:
    secretsFile: kms-secrets/kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(./kms-secrets/kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: api
        method: post
        cors: true
        authorizer:
          arn: ${env:COGNITO_ARN}
  playground:
    handler: src/handler.playgroundHandler
    events:
    - http:
        path: playground
        method: get
        cors: true
  graphiql:
    handler: src/handler.graphiqlHandler
    events:
    - http:
        path: graphiql
        method: get
        cors: true
