service:
  name: precisely
  # awsKmsKeyArn: ${self:provider.vars.kmsKeyArn}

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${file(../serverless/common.yml):stage} #${opt:stage, env:STAGE, "dev"}
  region: ${opt:region, env:REGION, "us-east-1"}
  profile: ${opt:profile, env:PROFILE, self:provider.vars.defaultProfile}
  deploymentBucket: ${self:provider.vars.account}-precisely-deployment-bucket

  # Store commonly used or noteworthy values here

  vars:
    account: ${file(../serverless/common.yml):account}
    accountFromStage: ${file(../serverless/common.yml):accountFromStage}
    accountId: ${file(../serverless/common.yml):accountId}

    authorizerTTL:
      dev: ${env:AUTHORIZER_TTL, self:provider.vars.authorizerTTL.devDefault}
      default: 300
      devDefault: 0

    certificateName: "${file(../serverless/common.yml):certificateName}"
    certificateMap: "${file(../serverless/common.yml):certificateMap}"

    graphQLAPIPath: "/api"

    auth0TenantName: "${file(../serverless/common.yml):auth0TenantName}"
    auth0TenantNameMap: "${file(../serverless/common.yml):auth0TenantNameMap}"

    auth0APIIdentifier: https://${self:provider.vars.account}-precise.ly/graphql/api

    # default AWS config profile name (used locally)
    defaultProfile: "${file(../serverless/common.yml):defaultProfile}"

    # customDomain / Route53 config
    domain: ${file(../serverless/common.yml):domain}
    domainMap:
      prod: api.precise.ly
      offline: localhost
      default: ${self:provider.stage}-api.codeprecisely.net

    # S3 resource names
    geneticsVCFBucket: ${self:provider.stage}-precisely-genetics-vcf
    userUploadBucket: ${self:provider.stage}-precisely-user-upload
    ingestionErrorBucket: ${self:provider.stage}-precisely-ingestion-error

    # Ingestion ECS Fargate Task
    ingestionECSTaskDefinitionName: ${self:provider.stage}-IngestionECSTaskDefinition
    ingestionContainerName: ${self:provider.stage}-IngestionContainerName
    ingestionClusterName: ${self:provider.stage}-IngestionECSClusterName

    logLevel: ${self:provider.vars.logLevels.${self:provider.stage},
                    self:provider.vars.logLevels.default}
    logLevels:
      prod: INFO
      default: DEBUG

    nodeEnv:
      beta: production
      prod: production
      default: development
      # otherwise NODE_ENV it will be "development"


  ##
  ## Environment for handlers
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${self:provider.vars.accountId}

    LOG_LEVEL: ${self:provider.vars.logLevel}
    # NODE_ENV should only be "production" OR "development"
    # See: https://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production
    #      https://webpack.js.org/guides/production/#specify-the-environment
    # We set NODE_ENV automatically based on STAGE:
    #   production for beta and prod
    #   development for all other stages
    # Override by passing it as env var:
    #   NODE_ENV={production|development} yarn sls ...
    NODE_ENV: ${env:NODE_ENV, self:provider.vars.nodeEnv.${self:provider.stage}, self:provider.vars.nodeEnv.default }

    # S3 buckets
    S3_BUCKET_GENETICS_VCF: ${self:provider.vars.geneticsVCFBucket}
    S3_BUCKET_USER_UPLOAD: ${self:provider.vars.userUploadBucket}
    S3_BUCKET_INGESTION_ERROR: ${self:provider.vars.ingestionErrorBucket}

    DOMAIN: ${self:provider.vars.domain}
    GRAPHQL_API_PATH: ${self:provider.vars.graphQLAPIPath}

    # Auth0 values - needed for verifying Auth0 tokens
    AUTH0_TENANT_NAME: ${self:provider.vars.auth0TenantName} # set in Auth0: dev-precisely, beta-precisely, prod-precisely
    AUTH0_API_IDENTIFIER: ${self:provider.vars.auth0APIIdentifier}

    # Quick and dirty way to define admins for now
    # TODO: better approach
    ADMIN_EMAILS: "aneil@precise.ly,vishesh@causecode.com"

    DYNAMODB_LOCAL_ENDPOINT: http://localhost:${self:custom.dynamodb.start.port}

resources:
  - Resources: ${file(./serverless/resources/roles.yml)}
  - Resources: ${file(./serverless/resources/cors.yml)}
  - Resources: ${file(./serverless/resources/dynogels-tables.js):Definitions}
  - Resources: ${file(./serverless/resources/s3-buckets.yml)}
  - Resources: ${file(./serverless/resources/logs.yml)}
  - Resources: ${file(./serverless/resources/ecs-fargate.yml)}
  - Resources: ${file(./serverless/resources/network/subnet.yml)}
  - Resources: ${file(./serverless/resources/network/routes.yml)}
  - Resources: ${file(./serverless/resources/network/gateway.yml)}

plugins:
  # Comment out the `serverless-domain-manager` line
  # on first-time deployment of a new stage, then uncomment it and redeploy
  - serverless-domain-manager
  - serverless-webpack
  - serverless-api-stage
  - serverless-dynamodb-local
  - serverless-shell
  - serverless-pseudo-parameters
  - serverless-offline # serverless-offline must be last in the list

custom:
  customDomain:
    domainName: ${self:provider.vars.domain}
    #basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: ${self:provider.vars.certificateName}
    endpointType: regional
  dynamodb: # dynamodb-local settings
    start:
      port: 8000
      inMemory: true
      migrate: true
      # seed: true
  stageSettings: # serverless-api-stage plugin
    ${self:custom.stageSettingsMap.${self:provider.vars.account}, self:custom.stageSettingsMap.default}

  stageSettingsMap:
    dev:
      MethodSettings:
        LoggingLevel: INFO # INFO ERR or NONE
        CachingEnabled: false
    default:
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MethodSettings:
        LoggingLevel: INFO # INFO ERR or NONE
        CachingEnabled: true
        CacheTtlInSeconds: 3600

  webpackIncludeModules: true

functions:
  APIAuthorizer:
    role: PreciselyDefaultRole
    handler: src/services/auth/handlers.apiAuthorizer
    cors: true

  GraphQLPlayground:
    role: PreciselyDefaultRole
    handler: src/services/graphql/handlers.playgroundHandler
    events:
      - http:
          path: ${self:provider.vars.graphQLAPIPath}
          method: get
          cors: true

  GraphQLAPI:
    role: PreciselyGraphQLAPIRole
    handler: src/services/graphql/handlers.apiHandler
    events:
      - http:
          path: ${self:provider.vars.graphQLAPIPath}
          method: post
          cors: true
          authorizer:
            name: APIAuthorizer
            type: request
            resultTtlInSeconds: ${self:provider.vars.authorizerTTL.${self:provider.vars.account},self:provider.vars.authorizerTTL.default}

  # VCF ingester is triggered by new file in S3_BUCKET_GENETICS_VCF
  VCFIngester:
    handler: src/services/genetics-pipeline/handlers.vcfIngester
    events:
      - s3:
          bucket: GeneticsVCF
          event: s3:ObjectCreated:*

  # Raw data uploader is triggered by new file in any of the raw data buckets
  RawDataUpload:
    handler: src/services/genetics-pipeline/handlers.rawDataUpload
    environment:
      INGESTION_CLUSTER: ${self:provider.vars.ingestionClusterName}
      INGESTION_TASK_NAME: ${self:provider.vars.ingestionECSTaskDefinitionName}
      INGESTION_CONTAINER_NAME: ${self:provider.vars.ingestionContainerName}
      SUBNET_ONE:
        Ref: DefaultSubnetOne
      SUBNET_TWO:
        Ref: DefaultSubnetTwo

    role: 
      'Fn::GetAtt': ["RawUploadLambdaRole", "Arn"]
    events:
      - s3:
          bucket: UserUpload
          event: s3:ObjectCreated:*
