service:
  name: precisely-backend

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.common.stage}
  region: ${self:custom.common.region}
  profile: ${self:custom.common.profile}
  deploymentBucket: ${self:custom.common.account}-precisely-deployment-bucket

  ##
  ## Environment for handlers
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    ACCOUNT_ID: ${self:custom.common.accountId}

    LOG_LEVEL: ${self:custom.vars.logLevel}
    # NODE_ENV should only be "production" OR "development"
    # See: https://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production
    #      https://webpack.js.org/guides/production/#specify-the-environment
    # We set NODE_ENV automatically based on STAGE:
    #   production for beta and prod
    #   development for all other stages
    # Override by passing it as env var:
    #   NODE_ENV={production|development} yarn sls ...
    NODE_ENV: ${env:NODE_ENV, self:custom.vars.nodeEnv}

    # S3 buckets - the S3_BUCKET_ prefix follows the convention of serverless
    S3_BUCKET_BIOINFORMATICS_VCF: ${self:custom.vars.bioinformaticsVCFBucket}
    S3_BUCKET_BIOINFORMATICS_UPLOAD: ${self:custom.vars.bioinformaticsUploadBucket}
    S3_BUCKET_BIOINFORMATICS_ERROR: ${self:custom.vars.bioinformaticsErrorBucket}

    BASE_DOMAIN: ${self:custom.common.baseDomain} # the root domain, adjusted for developer environments
    GRAPHQL_API_PATH: ${self:custom.common.graphQLAPIPath}

    # Auth0 values - needed for verifying Auth0 tokens
    AUTH0_TENANT_NAME: ${self:custom.common.auth0Tenant} # set in Auth0: dev-precisely, beta-precisely, prod-precisely
    AUTH0_API_IDENTIFIER: https://${self:custom.common.account}-precise.ly/graphql/api

    # Quick and dirty way to define admins for now
    # TODO: better approach
    ADMIN_EMAILS: "aneil@precise.ly,vetoshev@gmail.com"

resources:
  - Resources: ${file(./serverless/resources/roles.yml)}
  - Resources: ${file(./serverless/resources/cors.yml)}
  - Resources: ${file(./serverless/resources/dynogels-tables.js):Definitions}
  - Resources: ${file(./serverless/resources/s3-buckets.yml)}
  - Resources: ${file(./serverless/resources/logs.yml)}
  - Resources: ${file(./serverless/resources/bioinformatics-ecs.yml)}
  - Resources: ${file(./serverless/resources/apigateway-stage.yml)}
  
plugins:
  - serverless-domain-manager
  - serverless-plugin-bind-deployment-id # required for APIGatewayStage resource
  - serverless-webpack
  - serverless-dynamodb-local # this version installs dynamodb to project root by default
  - serverless-plugin-scripts
  - serverless-plugin-git-variables
  - serverless-offline # serverless-offline must be last in the list

custom:
  common: ${file(../serverless/common.js):vars}

  vars:
    authorizerTTL: ${env:AUTHORIZER_TTL,self:custom.vars.authorizerTTLMap.${self:custom.common.account},self:custom.vars.authorizerTTLMap.default}
    authorizerTTLMap:
      dev: 0
      default: 300

    fullSubnetId: ${self:custom.vars.fullSubnetIdMap.${self:custom.common.account}}
    fullSubnetIdMap: 
      dev: subnet-0c24e47887ea829f2
      stage: not-yet-provisioned-see-serverless-yml # TODO: manually generate PreciselyDefaultVPC and FullSubnet-PreciselyDefaultVPC
      prod: not-yet-provisioned-see-serverless-yml  #       ditto for prod

    nodeEnv: ${env:NODE_ENV, self:custom.vars.nodeEnvMap.${self:custom.common.account}}
    nodeEnvMap:
      dev: development
      prod: production
      beta: production

    logLevel: ${env:LOG_LEVEL, self:custom.vars.logLevelMap.${self:custom.common.account}}
    logLevelMap:
      prod: INFO
      beta: INFO
      dev: DEBUG
      offline: DEBUG

    # S3 resource names
    bioinformaticsVCFBucket: ${self:provider.stage}-precisely-bioinformatics-vcf
    bioinformaticsUploadBucket: ${self:provider.stage}-precisely-bioinformatics-upload
    bioinformaticsErrorBucket: ${self:provider.stage}-precisely-bioinformatics-error

    # Bioinformatics ECS Fargate Task
    bioinformaticsECSTaskDefinitionName: ${self:provider.stage}-BioinformaticsECSTaskDefinition
    bioinformaticsContainerName: ${self:provider.stage}-BioinformaticsContainerName
    bioinformaticsClusterName: ${self:provider.stage}-BioinformaticsECSClusterName

  customDomain: # domain-manager settings - for the api
    domainName: ${self:custom.common.apiDomain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: ${self:custom.common.certificateName}
    endpointType: regional

  dynamodb: # dynamodb-local settings
    start: ${self:custom.dynamodbMode.${env:DYNAMODB_MODE, "disk"}}

  dynamodbMode:
    memory:
      port: ${env:DYNAMODB_LOCAL_PORT, "8000"}
      migrate: true
      inMemory: true
    disk:
      port: ${env:DYNAMODB_LOCAL_PORT, "8000"}
      migrate: true
      dbPath: .
      sharedDb: true

  scripts:
    commands:
      console: ts-node -r tsconfig-paths/register
      env: env
      test: node_modules/.bin/jest -t '${opt:t, ''}' --env=jsdom --runInBand '${opt:f, ""}'
      test:watch: node_modules/.bin/jest -t '${opt:t, ''}' --env=jsdom --runInBand --watch '${opt:f, ""}'
      test:coverage: node_modules/.bin/jest -t '${opt:t, ''}' --env=jsdom --runInBand --coverage '${opt:f, ""}'
      seed:genetics: ts-node -r tsconfig-paths/register src/db/seed/cli.ts genetics "${opt:user, ''}" "${opt:genetics, ''}"
      seed:variant: ts-node -r tsconfig-paths/register src/db/seed/cli.ts variant "${opt:user, ''}" "${opt:variant, ''}"
      seed:reports: ts-node -r tsconfig-paths/register src/db/seed/cli.ts reports
      seed:clear: ts-node -r tsconfig-paths/register src/db/seed/cli.ts clear ${opt:model, opt:models, ""}
    
  serverless-offline:
    port: ${self:custom.common.offlineAPIPort}

  stageSettings: # serverless-api-stage plugin
    ${self:custom.stageSettingsMap.${self:custom.common.account}, self:custom.stageSettingsMap.default}

  stageSettingsMap:
    dev:
      MethodSettings:
        LoggingLevel: INFO # INFO ERR or NONE
        CachingEnabled: false
    default:
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MethodSettings:
        LoggingLevel: INFO # INFO ERR or NONE
        CachingEnabled: true
        CacheTtlInSeconds: 3600

  webpack:
    includeModules: true # auto-pack Node modules
    packager: 'yarn'     # Packager that will be used to package your external modules

functions:
  APIAuthorizer:
    role: DefaultRole
    handler: src/services/auth/handlers.apiAuthorizer
    cors: true

  GraphQLPlayground:
    role: DefaultRole
    handler: src/services/graphql/handlers.playgroundHandler
    events:
      - http:
          path: ${self:custom.common.graphQLAPIPath}
          method: get
          cors: true

  GraphQLAPI:
    role: GraphQLAPIRole
    handler: src/services/graphql/handlers.apiHandler
    events:
      - http:
          path: ${self:custom.common.graphQLAPIPath}
          method: post
          cors: true
          authorizer:
            name: APIAuthorizer
            type: request
            resultTtlInSeconds: ${self:custom.vars.authorizerTTL}

  # Raw data uploader is triggered by new file in any of the raw data buckets
  BioinformaticsUploadProcessor:
    role: SystemRole
    handler: src/services/bioinformatics/handlers.uploadProcessor
    environment:
      BIOINFORMATICS_CLUSTER: ${self:custom.vars.bioinformaticsClusterName}
      BIOINFORMATICS_TASK_NAME: ${self:custom.vars.bioinformaticsECSTaskDefinitionName}
      BIOINFORMATICS_CONTAINER_NAME: ${self:custom.vars.bioinformaticsContainerName}
      FULL_SUBNET: FullSubnet-PreciselyDefaultVPC # manually created
    events:
      - s3:
          bucket: BioinformaticsUpload
          event: s3:ObjectCreated:*

  SysAddNewVariantRequirementsFromReports:
    role: SystemRole
    handler: src/services/system/handlers.addNewVariantRequirementsFromReports
    timeout: 120
      
  SysUpdateVariantRequirementStatuses:
    role: SystemRole
    handler: src/services/system/handlers.updateVariantRequirementStatuses
    timeout: 120
    
  SysGetVariantRequirements:
    role: SystemRole
    handler: src/services/system/handlers.getVariantRequirements
    timeout: 120

  VariantCallBatchCreate:
    role: SystemRole
    handler: src/services/variant-call/handlers.batchCreate
    timeout: 120
