CloudFrontDistribution:
  Type: 'AWS::CloudFront::Distribution'
  Properties:
    DistributionConfig:
      Aliases:
        - ${self:provider.vars.domain}
      # Adding `stage` name as a Comment so that invalidation script can detect the stage by looking at the distribution
      Comment: ${self:provider.stage}
      DefaultRootObject: 'index.html'
      CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 500
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 501
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 502
          ResponseCode: 200
          ResponsePagePath: /index.html
      DefaultCacheBehavior:
        AllowedMethods:
          - GET
          - HEAD
        CachedMethods:
          - GET
          - HEAD
        Compress: true
        DefaultTTL: 86400
        ForwardedValues:
          QueryString: false
        MaxTTL: 31536000
        MinTTL: 0
        SmoothStreaming: false
        TargetOriginId: ${self:provider.vars.originId}
        ViewerProtocolPolicy: 'redirect-to-https'
      Enabled: true
      ViewerCertificate:
        AcmCertificateArn: arn:aws:acm:us-east-1:416000760642:certificate/f44b4ee7-b4cb-4d32-9c19-58ca6a97b42d
        # https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ViewerCertificate.html#cloudfront-Type-ViewerCertificate-SSLSupportMethod
        SslSupportMethod: vip 
      Origins:
        - Id: ${self:provider.vars.originId}
          DomainName: "${self:provider.vars.distributionBucket}.s3.amazonaws.com"
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: match-viewer 
