CloudFrontDistributionReactClient:
  Type: AWS::CloudFront::Distribution
  DependsOn: [ S3BucketReactClient, S3OriginAccessIdentityReactClient]
  Properties:
    DistributionConfig:
      Aliases:
        - ${self:custom.vars.clientDomain}
      Comment: Available at ${self:custom.vars.clientDomain}
      DefaultRootObject: 'index.html'
      CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 403
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 500
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 501
          ResponseCode: 200
          ResponsePagePath: /index.html
        - ErrorCode: 502
          ResponseCode: 200
          ResponsePagePath: /index.html
      DefaultCacheBehavior:
        AllowedMethods:
          - GET
          - HEAD
        CachedMethods:
          - GET
          - HEAD
        Compress: true
        DefaultTTL: ${self:custom.vars.cloudfrontDefaultTTL}
        ForwardedValues:
          QueryString: false
        MaxTTL: 31536000
        MinTTL: 0
        SmoothStreaming: false
        TargetOriginId: ${self:custom.vars.cloudfrontOriginId}
        ViewerProtocolPolicy: 'redirect-to-https'
      Enabled: true
      ViewerCertificate:
        AcmCertificateArn: ${self:custom.common.certificateArn}
        # https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ViewerCertificate.html#cloudfront-Type-ViewerCertificate-SSLSupportMethod
        SslSupportMethod: sni-only
      Origins:
        - Id: ${self:custom.vars.cloudfrontOriginId}
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Join:
                - ''
                - - origin-access-identity/cloudfront/
                  - Ref: S3OriginAccessIdentityReactClient
          DomainName:
            Fn::GetAtt: [ S3BucketReactClient, DomainName ]

S3OriginAccessIdentityReactClient:
  Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  Properties:
    CloudFrontOriginAccessIdentityConfig:
      Comment: Used to provide access to React S3 bucket from CloudFront