DefaultRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
    VpcId:
      Ref: DefaultVPC

DefaultInternetRoute:
  Type: AWS::EC2::Route
  Properties:
    DestinationCidrBlock: '0.0.0.0/0'
    RouteTableId:
      Ref: DefaultRouteTable
    GatewayId:
      Ref: DefaultInternetGateway

# The below two resources are required to explicitly associate
# the subnet with the Route table. If not done, the Route tables
# are created, but the rules are not applied on the subnets.
DefaultSubnetRouteTableAssociationOne:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    RouteTableId:
      Ref: DefaultRouteTable
    SubnetId:
      Ref: DefaultSubnetOne

DefaultSubnetRouteTableAssociationTwo:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    RouteTableId:
      Ref: DefaultRouteTable
    SubnetId:
      Ref: DefaultSubnetTwo