#!/bin/bash

#
# This file selects an environment and runs a command based on
# the ENV variable, as follows:
#
# IF ENV is defined,
#   use {ENV}.env
# ELSE
#   use default.env
#
#
set -a
CONFIG_DIR=$(cd `dirname $0` && pwd)
if [ -z "${1}" ]; then
  # if no command provided, withenv prints the env after loading the environment file
  SCRIPT="env"
else
  SCRIPT="${1}"
fi
shift
envfile="${CONFIG_DIR}/${ENV}.env"

if [ -f "$envfile" ]; then
  ENVFILE="${ENV}.env"
else
  echo -e "\033[93mCan't find ENV file: $envfile"
  exit -1
fi

echo -e "\033[93mLoading ${ENVFILE} environment"
source "${CONFIG_DIR}/${ENVFILE}"
"${SCRIPT}" "${@}"