#!/bin/bash
APPBACKEND_DIR=$(cd `dirname $0`/.. && pwd)
OUTPUT=${APPBACKEND_DIR}/serverless/generated/dynogels-tables.json

source ${APPBACKEND_DIR}/config/defaults.env
if [ -z "$1" ]; then
  echo "usage: deploy stage [region]"
  echo "stage=serverless stage, region=aws region"
  exit 1
else
  export STAGE="$1"
fi
if [ ! -z "$2" ]; then
  REGION="$2"
fi
export REGION

set -e
export TS_NODE_COMPILER_OPTIONS='{"module":"commonjs"}'
ts-node -r tsconfig-paths/register ${APPBACKEND_DIR}/scripts/write-dynogels-tables.js ${OUTPUT}

sls deploy -s $STAGE -r $REGION
