#!/bin/bash
APPBACKEND_DIR=$(cd `dirname $0`/.. && pwd)
if [ ! -d $APPBACKEND_DIR/node_modules/dynamodb-localhost/dynamodb/bin ]; then
  yarn sls dynamodb install
fi


check_process() {
  echo "$ts: checking $1"
  [ "$1" = "" ]  && return 0
  [ `pgrep -f $1` ] && return 1 || return 0
}

STAGE=offline yarn sls offline start