#!/bin/bash

# If STAGE variable is not set, this script loads environment
# provided in config/default.env

APPBACKEND_DIR=$(cd `dirname $0`/.. && pwd)

if [ -z "$STAGE" ]; then
  env-cmd ../config/default.env ${APPBACKEND_DIR}/node_modules/.bin/sls $@
elif [ -f ../config/${STAGE}.env ]; then
  env-cmd ../config/${STAGE}.env ${APPBACKEND_DIR}/node_modules/.bin/sls $@
else
  ${APPBACKEND_DIR}/node_modules/.bin/sls $@
fi